name: Docker
on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'docker/**/*'
jobs:
  lint:
    name: Run Hadolint checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: docker/Dockerfile      
          config: docker/.hadolint.yaml
      
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Retrieve version
        id: version
        run: |
          echo "::set-output name=label::$(python -m setup -V)"

      - name: docker build
        uses: docker/build-push-action@v2
        with:
          context: docker
          build-args: "GIT_VERSION=${{ github.sha }}"
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/arm-software/avhclient:main
          labels: "version=${{ steps.version.outputs.label }}"
