name: Integration Tests
on:
  workflow_run:
    workflows:
      - Build
    types:
      - requested
jobs:
  test_matrix:
    strategy:
      matrix:
        region: [ eu-west-1, us-east-1 ]
        include:
          - region: eu-west-1
            # secret names
            AWS_S3_BUCKET_NAME: AWS_S3_BUCKET_NAME
            AWS_SECURITY_GROUP_ID: AWS_SECURITY_GROUP_ID
            AWS_SUBNET_ID: AWS_SUBNET_ID
          - region: us-east-1
            # secret names
            AWS_S3_BUCKET_NAME: TEST_AWS_S3_BUCKET_NAME
            AWS_SECURITY_GROUP_ID: TEST_AWS_SECURITY_GROUP_ID
            AWS_SUBNET_ID: TEST_AWS_SUBNET_ID
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    env:
      PR_HEAD_SHA: 0
    steps:
      - name: Get PR data
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          env
          pull_requests=${{ github.event.workflow_run.pull_requests }}
          echo $pull_requests
          head_sha=gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${GITHUB_REPOSITORY}/pulls/${pull_requests}
          echo ${head_sha}
          echo "PR_HEAD_SHA=${head_sha}" >> $GITHUB_ENV

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          ref: "${{ env.PR_HEAD_SHA }}"

      - name: Checkout AVH-GetStarted example
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: AVH-GetStarted
          ref: main
          repository: ARM-software/AVH-GetStarted

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install AVH Client
        run: pip install .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::720528183931:role/Proj-vht-assume-role
          aws-region: ${{ matrix.region }}

      - name: AWS STS
        run: |
          env
          aws sts assume-role-with-web-identity --role-arn arn:aws:iam::720528183931:role/Proj-vht-assume-role --region eu-west-1 --role-session-name GitHubTest --web-identity-token $ACTIONS_ID_TOKEN_REQUEST_TOKEN
          aws sts get-caller-identity

      - name: Run tests
        id: avh
        env:
          AWS_DEFAULT_REGION: ${{ matrix.region }}
          AWS_S3_BUCKET_NAME: ${{ secrets[matrix.AWS_S3_BUCKET_NAME] }}
          AWS_SECURITY_GROUP_ID: ${{ secrets[matrix.AWS_SECURITY_GROUP_ID] }}
          AWS_SUBNET_ID: ${{ secrets[matrix.AWS_SUBNET_ID] }}
        run: |
          avhclient -b aws execute --specfile AVH-GetStarted/basic/avh.yml
