name: Integration Tests
on:
  workflow_run:
    workflows:
      - Caller Integration Tests
    types:
      - completed
jobs:
  test_matrix:
    strategy:
      matrix:
        region: [ eu-west-1, us-east-1 ]
        include:
          - region: eu-west-1
            # secret names
            AWS_S3_BUCKET_NAME: AWS_S3_BUCKET_NAME
            AWS_SECURITY_GROUP_ID: AWS_SECURITY_GROUP_ID
            AWS_SUBNET_ID: AWS_SUBNET_ID
          - region: us-east-1
            # secret names
            AWS_S3_BUCKET_NAME: TEST_AWS_S3_BUCKET_NAME
            AWS_SECURITY_GROUP_ID: TEST_AWS_SECURITY_GROUP_ID
            AWS_SUBNET_ID: TEST_AWS_SUBNET_ID
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: caller-integration-tests.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Read the pr_num file
        id: pr_num_reader
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: ./pr_number/pr_number
          trim: true

      - name: Clone this repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh pr checkout ${{ steps.pr_num_reader.outputs.content }}

      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Integration Test
          conclusion: in_progress
          output: |
            {"summary":"in_progress"}

      - name: Checkout AVH-GetStarted example
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: AVH-GetStarted
          ref: main
          repository: ARM-software/AVH-GetStarted

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install AVH Client
        run: pip install .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ matrix.region }}

      - name: Run tests
        id: avh
        env:
          AWS_DEFAULT_REGION: ${{ matrix.region }}
          AWS_S3_BUCKET_NAME: ${{ secrets[matrix.AWS_S3_BUCKET_NAME] }}
          AWS_SECURITY_GROUP_ID: ${{ secrets[matrix.AWS_SECURITY_GROUP_ID] }}
          AWS_SUBNET_ID: ${{ secrets[matrix.AWS_SUBNET_ID] }}
          AWS_IAM_PROFILE: ${{ secrets.AWS_IAM_PROFILE }}
        run: |
          avhclient -b aws execute --specfile AVH-GetStarted/basic/avh.yml

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Integration Test
          conclusion: ${{ job.status }}
          output: |
            {"summary":${{ steps.test.outputs.summary }}}
